# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_regex
    test_fault_wrappers_string
    test_fault_wrappers_wchar
    test_fault_wrappers_wctype
    test_fault_wrappers_wordexp
)
