# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_p101_locale_iconv
    test_fault_wrappers_p101_locale_locale
    test_fault_wrappers_p101_locale_nl_types
    test_fault_wrappers_p101_text_regex
    test_fault_wrappers_p101_text_string
    test_fault_wrappers_p101_text_wchar
    test_fault_wrappers_p101_text_wctype
    test_fault_wrappers_p101_text_wordexp
)
